### ISSUE TITLE
Wrapping member fields on MonoBehaviour objects will cause errors with deserialization when exported with standalone player

### ISSUE THREAD

**Issue by BrunoSilvaFreire** [clonegames/Chess#2]
As seen [here](https://github.com/clonegames/Chess/blob/master/Assets/Assets/Game/Scripts/Chessboard.cs#L35-L37):
```csharp
    [RequireComponent(typeof(BoxCollider))]
    public class Chessboard : Utilities.Singleton<Chessboard> {
        // ...
        #region TemporaryFields
        public bool DrawGizmos;
        #endregion
        // ...
}
```
Wrapping field members in `#if` statements will cause problems at standalone runtime during deserialization, due to the field being missing, but being serialized at build-time.

Just a warning due to the "TemporaryField" naming.

**Comment by Kadowns** [comment]
done :ok_hand:
